[colors.bright]
black = "#3B4252"
blue = "#88C0D0"
cyan = "#93CCDC"
green = "#B1D196"
magenta = "#C895BF"
red = "#D06F79"
white = "#E5E9F0"
yellow = "#F0D399"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black = "#191D24"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#D8DEE9"
yellow = "#EBCB8B"

[colors.primary]
background = "#22262c"
dim_foreground = "#a5abb6"
foreground = "#D8DEE9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#6F9AA7"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#D8DEE9"
text = "#2e3440"

[env]
TERM = "xterm-256color"

[font]
size = 9.5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[shell]
args = ["-e", "try { zellij attach default } catch { zellij -s default }"]
program = "/usr/bin/nu"

[window.dimensions]
columns = 140
lines = 38
